### ISSUE TITLE
Strange report in 1.9?2 paperspigot

### ISSUE THREAD

**Issue by belfedia** [Vastrix/Offline-Teleporter#6]
Hello, thanks to your work, this plugin is the only one !

I use last paperspigot 1.9.2 and i have this strange report, plugin is working but strange

```
2016-05-13 19:58:15 [INFO] nanard issued server command: /otp dowena
2016-05-13 19:58:15 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'otp' in plugin Offline_Teleporter v0.5
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.2.jar:git-Paper-727]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.9.2.jar:git-Paper-727]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched_1.9.2.jar:git-Paper-727]
    at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1388) [patched_1.9.2.jar:git-Paper-727]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched_1.9.2.jar:git-Paper-727]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.2.jar:git-Paper-727]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.2.jar:git-Paper-727]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-727]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-727]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:813) [patched_1.9.2.jar:git-Paper-727]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-727]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.2.jar:git-Paper-727]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.2.jar:git-Paper-727]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoSuchFieldError: ENDERMAN_TELEPORT
    at com.gmail.sevrius.OfflineTeleporter.OfflineTeleporter.onCommand(OfflineTeleporter.java:157) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.2.jar:git-Paper-727]
    ... 15 more
```

Could you help me ? :)

**Comment by Willsr71** [comment]
You are still using the 1.7 version, try updating to [version 0.6](https://jenkins.willsr71.net/job/OfflineTeleporter/) and see if that works.

**Comment by Vastrix** [comment]
Yea, I should've updates the bukkit page..
Anyways, Done that so it's all up-to-date now :)

Thanks Will ;)

**Comment by belfedia** [comment]
Thanks, i don't know this jenkins :) No more message now :)
